[package]
name = "time-windows"
version = "0.1.0"
authors = ["Brandon W Maister <bwm@materialize.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"
anyhow = "1.0.34"
