# Copyright Materialize, Inc. All rights reserved.
#
# Use of this software is governed by the Business Source License
# included in the LICENSE file at the root of this repository.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0.
copyright: 'Copyright Materialize, Inc.'

dev_addr: '0.0.0.0:8765'

docs_dir: 'handbook'

edit_uri: 'edit/main/performance/handbook/handbook'

markdown_extensions:
    - admonition
    - codehilite:
        linenums: true
    - toc:
        permalink: true

nav:
    - Home:
        - index.md
    - Guides:
        - guides/building.md

plugins:
    - search

repo_url: 'https://github.com/MaterializeInc/materialize'

site_name: 'Materialize Performance Handbook'
site_description: 'Handbook for Materialize developers work on materialized performance'
site_author: 'Materialize'
site_url: 'https://www.materialize.com'

theme:
    favicon: 'static/favicon.ico'
    features:
        - tabs
    font:
        text: 'Maven Pro'
    logo: 'static/logo_white.png'
    name: 'material'
    palette:
        primary: 'deep purple'
        secondary: 'lime'
