# Copyright Materialize, Inc. All rights reserved.
#
# Use of this software is governed by the Business Source License
# included in the LICENSE file at the root of this repository.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0.

x-port-mappings:
  - &handbook ${HANDBOOK_PORT:-8765}

version: '3.7'
services:
  handbook-develop:
    mzbuild: perf-handbook-develop
    ports:
      - *handbook
    volumes:
      - type: bind
        source: ${MTRLZ_GIT_ROOT}/performance/handbook
        target: /src

mzconduct:
  name: perf-handbook
  workflows:
    develop:
      steps:
      - step: start-services
        services: [handbook-develop]
